"""
Django settings for pensdnd project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os

from pathlib import Path
import  pensdnd.my_secrets as keychain

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

cwd = os.getcwd()
if "adjutant" in cwd:
	"""
	We're in production. Act like it.
	"""

	DEBUG = False
	SECRET_KEY = keychain.secret_key
	ALLOWED_HOSTS = ["pensdnd.servegame.com"]
	DATABASES = {
		"default": {
			"ENGINE": "django.db.backends.postgresql",
			"NAME": "pensdnd",
			"USER": "adjutant",
			"PASSWORD": keychain.postgres_password,
			"HOST": "127.0.0.1",
			"PORT": "5432",
		}
	}

else:
	"""
	We're in development mode. Use the development key and sqlite.
	"""

	# SECURITY WARNING: don't run with debug turned on in production!
	DEBUG = True

	SECRET_KEY = keychain.devel_key
	ALLOWED_HOSTS = ["192.168.1.19",]

	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.sqlite3',
			'NAME': BASE_DIR / 'db.sqlite3',
		}
	}

	# Static files (CSS, JavaScript, Images)
	# https://docs.djangoproject.com/en/4.0/howto/static-files/

	STATIC_URL = 'static/'
	STATIC_ROOT = BASE_DIR / "pensdnd/static/"

	TEMPLATE_DIRS = (
		STATIC_ROOT / 'templates',
	)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
	'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
	'blog',
	'feedback',
	'application',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'pensdnd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
			STATIC_ROOT / 'templates',
			STATIC_ROOT / 'templates/partials',
		],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pensdnd.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
