# Generated by Django 4.0.4 on 2022-05-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_applicationmodel_tie_breaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='tie_breaker',
        ),
    ]
